[package]
name = "octo_rs"
version = "0.1.0"
edition = "2024"

[dependencies]

color-eyre = "0.6.3"
crossterm ="0.28.1"
ratatui = "0.29.0"
ratatui-textarea = "0.4"
tui-textarea = "0.7"
chrono = "0.4"
